name: prototype

on:
  push:
   branches:
      -main

  pull_request:
      -main
 
jobs:
  demo-jobs: build 
      runs-on : ubuntu-latest

    steps:
     -uses: checkout@v3
     -name: checkout repository

     -name: run a command 
      run : exit 1
